### ISSUE TITLE
Improve description of the event lib

### ISSUE THREAD

**Issue by alansemenov** [enonic-archive/old-xp-doc#108]
http://repo.enonic.com/public/com/enonic/xp/docs/6.15.2/docs-6.15.2-libdoc.zip!/module-event.html

Describe ``localOnly`` parameter of the ``listener`` method. Is it the opposite of ``distributed`` parameter of the ``send`` method?

**Comment by jsi** [comment]
Issue moved to [enonic/doc-xp #96](https://github.com/enonic/doc-xp/issues/96) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jsi** [comment]
Copied to doc-xp: https://github.com/enonic/doc-xp/issues/96
