### ISSUE TITLE
Not obvious how to search for content with datetime = null

### ISSUE THREAD

**Issue by Bellfalasch** [enonic-archive/old-xp-doc#37]
For docs about datetime searching.

After a lot of time CWE and RFO independently found out searching for content without any date set are done like this:

`query: 'data.published LIKE "*"'`

This not so straight forward approach needs to be documented in search datetime docs in a good way. A lot of time spent testing things back and forth until it works. If added to docs as an example and/or as extra section it would help others.

**Comment by jsi** [comment]
First, we need to verify that this is actually expected behaviour.

**Comment by Bellfalasch** [comment]
Very good point! CWE and RFO knows more about details here, I'm just making sure this is not lost as it occurred to me as a bit "odd" behaviour/approach.

**Comment by Bellfalasch** [comment]
6.10 introduces filters on queries. It is very handy and can do this. Should we add example on date searching page with info RMY / JSI? Example would be nice.

**Comment by Bellfalasch** [comment]
There's still nothing in the docs about searching for empty dates. It is a question that keeps popping up. We need to add info to the docs that we can refer to.
