### ISSUE TITLE
Link from Dev/Localize page to view function

### ISSUE THREAD

**Issue by Bellfalasch** [enonic-archive/old-xp-doc#42]
Localization is handy to use in the view directly. But there is no linking going from the general developer introduction here:
http://xp.readthedocs.io/en/latest/developer/i18n/index.html

... to the specific view function here:
http://xp.readthedocs.io/en/latest/reference/view-functions/localize.html

We should have a link here somewhere. A proper introduction page showing all possibilities.

Came up during a training session.

**Comment by jsi** [comment]
So, it is only the link that is missing?  Or are you saying the introduction is not "proper"?

**Comment by jsi** [comment]
At least link is now added for 6.10 and latest.  See if you think this is good enough.  If not, set this issue back to "In progress", otherwise, please set it to "Done".

**Comment by Bellfalasch** [comment]
Solves the issue yes.
