### ISSUE TITLE
Improve explanation of portal object

### ISSUE THREAD

**Issue by jsi** [enonic-archive/old-xp-doc#44]
This page: http://xp.readthedocs.io/en/stable/reference/view-functions/index.html is not very understandable.  It lacks context and an overview, and there should be a link to the JavaDoc (http://repo.enonic.com/public/com/enonic/xp/docs/6.11.0/docs-6.11.0-libdoc.zip!/module-portal.html), with an explanation of the difference between the 8 functions listed in doc and the 22 in the javadoc.  Also: please answer these questions that have come up in the courses we have held for customers, on that page:

 - Is "portal" a reserved name?
 - How and Where to use ${portal.something} in Thymeleaf
 - Architecture (where does portal object come from?)

**Comment by jsi** [comment]
@Bellfalasch requested this documentation.  It came up during a training session.   (Feedback from TDM meeting.)

**Comment by Bellfalasch** [comment]
@ComLock Does this look right? Since you got the questions you know best.

I guess 1) and 3) are the important ones, 2) is more or less covered as far as I know.
